### ISSUE TITLE
getting errors with data.table examples in PDF

### ISSUE THREAD

**Issue by sfd99** [eddelbuettel/gsir-te#2]
Hi Ed, 
Your new Tinyverse PDF "Getting started in R"
is truly great. 
_Thanks!_

But I'm  getting errors in Rstudio
with all **data.table** examples in that PDF.

ie:
> **cw[, weightKg := weight/1000 ]**
Error in `:=`(weightKg, weight/1000) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

Using Ubuntu Linux 32 bits w/ latest R and Rstudio...
and data.table PKG version 1.11.8
**_SFd99_
San Francisco**

**Comment by eddelbuettel** [comment]
I just re-run all on the train this morning and have, as you can imagine, been running this quite a bit.

What _should_ happen here is 
1. `library(data.table)`
2. `cw <- fread("ChickWeight.csv")`
and at that point `cw` is guaranteed to be a `data.table` object.  From your bug report it is not clear what you tried.  Did you do 1. and 2. ?

**Comment by sfd99** [comment]
thanks f/answering, Ed!.

Yes, you are abs right, 
I used the standard "ChickWeight" DF included in the environment,
and coerced it to a data.table, with:
  `as.data.table...`
then:
  `class(cw) # yes, it says IT IS a data.table!.`
But then, the ":=" examples commands in the PDF
didn''t work...

Now, importing the CSV file as you prescribe in the PDF,
with:
   `cw <- fread("ChickWeight.csv")`
EVERYTHING IS WORKING FINE! :-)

I just wonder why using the R-included 
 "ChickWeight" DF
and coercing it to a DT didn't work.
(ie,  the PDF ":="  examples would not work with _that_ DT...).

**Comment by eddelbuettel** [comment]
The name is Dirk, by the way.

I will commit the extracted source code as well as a file and in the zip archive. But you were not supposed to use the _existing_ `ChickWeight` variable.  I'll make that more clear.

Closing this though.  (And maybe do look at the "Styling with Markdown is supported" link here to leanr about Markdown.  Makes everything more readable.)

**Comment by sfd99** [comment]
Thanks 10^6, **Dirk**!!!
_Great tutorial!_
SFd99
San Francisco

**Comment by eddelbuettel** [comment]
@saghirb :  User 'sfd99' (oh how I dislike it when people hide behind anon handles...) raises a fair point. 

Shall we add  `cw <- setDT(as.data.frame(ChickWeight))` in at least a footnote or a sentence to offer `cw` direcly from the existing variable (along with continuing to show `fread()`) ?

**Comment by eddelbuettel** [comment]
@sfd99 `data.table` is different.  You _cannot_ just cast via `as....()`.  The canonical command is `setDT()` to convert an existing `data.frame` -- and in _this case_ it requires an initial copy as the variable is "locked" in the environment of the package it came from (and can not let `data.table`, operating 'by reference', alter it).

**Comment by sfd99** [comment]
**Thanks for that clarification, Dirk!**.
Now, finishing the data.table examples of 
this great tutorial..._.love it!_

**Comment by saghirb** [comment]
> Shall we add `cw <- setDT(as.data.frame(ChickWeight))` in at least a footnote or a sentence to offer `cw` direcly from the existing variable (along with continuing to show `fread()`) ?

Looking at `str(cw)` we see that both `Chick` and `Diet` are factors. The original reason I opted to export and read in the data was to start clean to avoid this historic feature (along with making reading in data a natural part of data analysis process). It was causing confusion in my courses (e.g. not being able to explain why chicks are an ordered factor variable). 

In a way the "Getting Started" guides as serving a similar purpose to "travel phrase books" for spoken languages. They give enough to let you get by whilst avoiding technical details (grammar) and exceptions. 

My vote is against including the above code as a footnote.

I am preparing a blog with my thoughts on the "Getting Started" guides. It needs more work (and time) at the moment.

**Comment by eddelbuettel** [comment]
Yes, agreed. I ended up with a softer addition making it just

>  First we will import the data from a file called `ChickWeight.csv` using the
`fread()` function from the `data.table` package which return you a
`data.table` object (whereas the dataset built into R in a different format).

(Edit: Oops. Should be "has a different format". Will fix.)

**Comment by saghirb** [comment]
Nice. I like it. 

Another minor edit as you're at it "which returns a data.table object".

**Comment by eddelbuettel** [comment]
Fixed in source.  Good catch.

(BTW:  Should we / could we re-merge the repos?  Or maybe put both into a new org GSiR or something like it?  Can leave as is too...)
