### ISSUE TITLE
Automate zip file creation

### ISSUE THREAD

**Issue by saghirb** [eddelbuettel/gsir-te#4]
I implemented a quick fix to automate the creation of the zip file for the [GSiR](https://github.com/saghirb/Getting-Started-in-R) repository. See my new [_runall.R](https://github.com/saghirb/Getting-Started-in-R/blob/master/_runall.R) file.

If you are happy with I can issue a similar pull request for gsir-te. Let me know.

**Comment by eddelbuettel** [comment]
It's ok.  We don't update the sources all that often, and it really is easy enough to create a zip file outside of R. Shall we close this?

**Comment by saghirb** [comment]
I was thinking more along the lines that if I create more of these guides (current four in progress) then I'd like takes out all manual steps where possible. However if you are fine to continue as is then that is fine with me to close this request.

**Comment by eddelbuettel** [comment]
Yes, I think this repo may just stay as it is for that document.
